<?php
include("Comparator.php");
//include("Motifs.php");
include("Sequence.php");

$txtpatr1=$_GET["inPatron"];
$txtDistancia=(floatval( $_GET["distancia"]))*0.01;
$txtNpares=intval($_GET["nPares"]);
$txtConservacion=(floatval($_GET["conservacion"]))*0.01;
// los tres genes ortólogos de Drosophila 
//DnaJ-1_melanogaster

$f1="AAATACTAAACGCATTGCAGCTGTGGCAATGCCCAAGTCTTGGTCTTACGGTCACACTGGCAAAGTTTAAAAATTTATTTATTTCAACTTTCAGTTACTTTTCGTTGGCTTGAATATTACACTAAGAATTCAATTTGACACTTGCAATTTATACATTGTATATTATAATATATTATATGTATTATATTTTATATCATATAAAGATATTTATATCTATTGATCTTTTGATTATAAGCTCTTTGGTTGAACAATATAAGTGCAACTTTCTCCATCACCTTCCTATCTTTTTACAATATGCTTACCTCGTCAATACGTTTTTTCTATTTCAAATATTTCAATATTTCAAAGAAATATTTTGTTTATTTTTCTGTGTGTTTTTAAGCAATCTGACCCCTGTAGAAGAATCCCTTATAATATTAACAAATGTATCCTCAAAATAGATCGATCTCTATCTTCGCAGACTTACACGAAACATTCCAGAACCGATAGTTTTATGCGATATATGAGATTTAAGGAGTACTTTCCGCATTTCGCCATCACAGTCACGCTTTCCTTGGCATTTGCAATCAAATAAGCGCTAATAATAATCGTAAAAGCATAAGAAGCATATAAAGAAGAGTCACCGCCAAAAGCATGCACAAATATATATAAATGGGGAGCGATTTAAAAACAGTGCACTGTGTTTAAAACATCGACAGCTATCGGTTAGCATATCGATATTGACATTCGCAGTCAAACGTTTTCGAGATACAACCCTAAAATCCGAGAAGCATCCAGAAATTT";
//>GA10408_D_pseudoobscura
$f2="TTTCGGTAGTCAAATGTTTTTTTTTTATTCTTTTTACGAAATTTTACACACAAAAGGCTGCTTCTGTTCTGGACAGAACGTCAGAAATGACGTTGCAGTTCTGCTAGGATTTGACATTTCAAATGAAATGTCAGTACAGGGCCTACTATTTCGATTATTCCTAAAACTTCTAGAGTTCATAGTAATATATAATATAATATGTATATAATTTAATATAATAAATAGTATAATATATAATATACTCACTTATTCCCACTTGAATTCCAGAAAGAGTTGAATTTTTGTATTCTTATTTGCACTTTCACTCACTTTTGGCCAGTAGAGCGTTTCATTTTTCACTTGACTTGAAGCCTAACGCGTGACGCACGCGCACAACTCTAGAATTTAAACGCACGTTTTAATTGTTGACCGCTTTGAATGAGGGACCGAGCGGGGGTGAACTGAGAAAGCTGTGATAAGAATGCAGCAGCGTGGCCGGCTCAAAGTACTAAATCCCCTAAGCTCATTTCAAAAAACG
//AGAGCGAAAGCTTGTTGTCGAACAATTGTTTACATATGTATGTATGTGAAGAGCGATAAAAGTGCATGCTCAAGGCTCTGCTTTGAAATCGACCTTTGTTTCTGTGTTTATCTTATCTCTCCCCATCTCATAGCAAAAGCGAGAGGGAAGAAGAGCATAATTCTCGCACATCGCTTTCTGTCGCTGTTAGCTCGCTGCTTAATTAACATCCATCTGTAACGACAGTAGAGCATTGGTTCTTTCTCTGTTAGCTCATTGAACACTATGCAGGGAATTCTGTTGAATATTACATAGTGTTTTCCTGTTGTCCCTCTTATCTGAACAATACTGATTTAAATGTTGGCGCTTAGAAGAAGAACGTTTGCATGCTAGCGCATGCATTCTACAATCCCTAAGTGTGGCCGCATTACAATCAATGATAGTCGATAGCATCGTGCAGTCAGATTTCCGTAGTCAGTATTTCAAGAACTCCCGCCTTCTTATCGGTTGTATCAGCGCTGTCATTCCACTGCAACTCTAAGCTGCGAGAAACATCGAGATATTTCGATGGGTAGACGGACTTCGGGCGATAGGCCATTTACGGTATACTATATACCTTTCTGTATATTGTGACGTCGATAAACTTTCATACGCTCTCTAACATAGTGCTTCCTTACATTATTTATTCCACAGGAGTGCATTTGTATCCTTTTCACTCATTCATTTTCAAGCAATTCCACTTTGGCGCGCAGTCGATAGTATCGATAGCCGTTTCTGTGAATTAATCATACTTAGGTTGACTCTTTTGCTTGAACCTTTTTTAGACACAGTCAAAAAAAGAAAACATCCTTAAATAGGACCATTCTTGAACAAAATTGATTCATCTATCGAAGAAAATTATGTCCTTAGGGCTGACAGTCCTAGATAGCTGATAATATTCAGCCGAATATCAAAATCGAGGAATACGATTTCCGATTATGGACAGAGAACGATTAACCCATTGTATTAAAATAAGCTCCACGAAAAAAATTAAATTCGAAGAATTTAGCGCAGTTCCGGTAAAAAATTTGGTAGTCATTATTTTTGTGTAAGAAAAAAAATATAAATATATTTACAAAGTATTTCCAAACAGTAGTATTTGCCATGGGTTACTGTAGCTGTCCACATAATTATATGAATGGGGGGCCTAAGTGGGTTAAGTTCTCCAAGCAGCGAGAAACATCGAGAAAATTCGACGAGCAGACGGAACAGAGTCTATATAAAGGCCTGCGATATTCGGGCGACAAACAAAAAAATTTTATCGACTGAGCAACAAGGGTGTGTGCTAACACAGCAAACGAGAAAAAAAATAAAATTGATTGAGAACGTCATCTATTATTTTCAAGAACGTGTAATATATATATATAAATAATACAAACTCGTACAACAGGAGAAAGAAAATTGAAAAGTGAAGTGGAAATAGTTTTAGCAAAGAGAAAACAGCATTTTAGGTGAGTAGTTTGTGGCAAAATGGAATTGATACTTTAAATTAACATATTCGCATGGCATTCCCAAATGCCTAATGTATGGTGTGTGATGTGTGGTGTGTGGGAGAATATTATATTAGTGACATGCACAGGGGCGGGCGGACGACGTAGCTCGTGGGGGAAAAATGACAACACATCAGCACCAGCACCAACCCAAGCGAAAGCACAGGGGCTGTGTCGTTGCACAACTCGGTGTTCTAGAAAATTCCATTGAAAAAACAATCGAAGCGAAGTGGTAATCAGTACACATGTTCTATAATATTCTCTGTATTCTCTGTTCGCTTTCAGGTTGAAAGAGACTGAACAAG";

//>GJ11949_Dvirilis
$f3="ACACATGTGATTGCTTAAGTGCGAAAAACTAGTTCAAGCTTTGCGTCCTTCAACGTCTTGGCCAAATGTCGGAAAACTTGCGGCTCCAAAATATGCTCGTTCACACATACACACATTTATATGTAGGCATACAGATACACATACATATGTATGATTTCACTCACCTGAACTGTGAAAATGTTGCAATATTGTGTTAGGGTTAAATGCACAATCCGGCCCAAGGGCTGGGACTACACAGGCCAATTGATTTGTTGCTATCTAAACTGTTTAAACGGAGGATGCTTGACGTTGATACCGAGCAGCAACCATTTTTATAAATGAAACAAATGTTTTTTGTTGTTCTGCTGCGGTTTGGCTGCAGTTCTATCGATGGCAATACCGATAAGCCTGCCTGCTATCGATGGTTATCCGATAGTTCCATCAGTCACCCTACACAAAGTATCGATGCTACGGCTGCAATTCGATTCAAATCAAATCGATTATTGATTTGTAACAAACGCAGTTAATTGACACACTATAATCCACAAATCAATAACCCATGCTTATTTAAATTCAATTTATCAACTAACATGCAATTTTTATGTTCTTAGCAAAATGATTTAAATATTTGAATTTTGGCGCTATATGTTATCGAACCGTTGTGTTCCGGATGCAACCCTATTATGCTAGAAGCATCGAGAATTTTCGACGAGCAGACTGCTCCGAGTCTATATAAAGGCAACATCCGTTGCCAGTTCGACTCATTTAGCAAAAATCAAGAGAAACGAGTAGTGGGTGTGTTTTCACACTAGATAAAAAAAACCAGAACTATTGATTAAAACCAATATAATTTCAAGAATATAGTGCATTTTTCAACTGCAATTCATAGAAATTCAAGTAATAATCAAATCGGAAAGTTAATTTACAAGAAAAAAGTAAAATAAAAAAAAAAAAAATAGCACGCAGCTGCAAAACAAAAAAGGTATGTAGGGCCTAACACATTAATTGTTGCTTAAATTAGCTTGTTTTCACTTGAAAACAAACTGCATTTAATGAACTTTAAAGCAAGAGATAAAATGAAAAGCCAAACAAGCAATACAATACAGTGAAATGTGAAATTTAAATCCCAAAACACAGCGGCGTCGACGTCACGCCCAGATTGACAACACATCAGCTTTTCGCTGGCGTTGTCTTTGTCGTTGCACAACTCAAAGTTTCTAGCAATTTCCATTGGGCGACGCGTTGAAAAAACAATCGACATATTTGTCTCTGCTGTTTTAGCTTTGCGTTTATAAATAAGTACATATATCAGTAGAATAATTGTGTGCTTTCTATTCTTTTTTCGCAGTTTGTAAGTGCGCGGCGTCAAATTAAAGCATA";


ini_set("display_errors", "On");
error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE | E_ALL | E_STRICT);


 $seq1= new Sequence();
 $seq2= new Sequence();
 $seq3= new Sequence();
 $part1 = new Sequence();

 $seq1->setSequence($f1);
 $seq2->setSequence($f2);
 $seq3->setSequence($f3);
 $part1->setSequence($txtpatr1);

// echo "<br>P1: ". $seq1->getSequence();
// echo "<br>P2: ". $seq2->getSequence();
// echo "<br>P3: ".$seq3->getSequence();
// echo "<br>PAt: ". $part1->getSequence();

 $comp= new Comparator($seq1,$part1); 
 $comp2= new Comparator($seq2,$part1); 
 $comp3= new Comparator($seq3,$part1); 

 echo "<br> R1 ".$resultSP1=$comp->getIndex();
 echo "<br> R2 ".$resultSP2=$comp2->getIndex();
 echo "<br> R3 ".$resultSP3=$comp3->getIndex();

//echo "<pre>".var_dump($resultSP1)."</pre><br>";
//echo "<pre>".var_dump($resultSP2)."</pre><br>";
//echo "<pre>".var_dump($resultSP3)."</pre><br>";

$reporte="<p><ol>";
/*$reporte.="<li> En Melanogarter <ul>";
$reporte.="<li> En Pseudoscura <ul>";
$reporte.="<li> En Virilis</li>";
$reporte.="</li>";
$reporte.="</ol></p>";
$reporte="<p><ol>";
*/

$cnt=0;
if (isset($resultSP1) && !empty($resultSP1) ) {
		$reporte.="<li> En Melanogarter <ul>";
			foreach ($resultSP1 as $key => $value) {
					$reporte.="<li>".$value."</li>";
			}
		$reporte.="</li>";
		$cnt++;
	if (isset($resultSP2) && !empty($resultSP2)) {	
		$reporte.="<li> En Pseudoscura <ul>";
			foreach ($resultSP2 as $key => $value) {
					$reporte.="<li>".$value."</li>";
			}
		$reporte.="</li>";
		$cnt++;
		if (isset($resultSP3) && !empty($resultSP3)) {
		$reporte.="<li> En Virilis</li>";
			foreach ($resultSP3 as $key => $value) {
					$reporte.="<li>".$value."</li>";
			}
		$reporte.="</li>";
		$cnt++;
	}
  }
}else{

	$reporte.="No existe patron en Melanogarter";
}

$reporte.="</ol></p>";

echo  "<br>Prueba de distancia";
if (isset($resultSP1) && !empty($resultSP1) && $cnt===3) {

 for ($i=0; $i <count($resultSP1) ; $i++) { 

	$radio = $txtDistancia*$resultSP1[$i];
	$rango[0]=$resultSP1[$i]-$radio;
	$rango[1]=$resultSP1[$i]+$radio;

 	if (count($resultSP2)!=0) { 		 
	 	for ($j=0; $j <count($resultSP2) ; $j++) {//segunda sequencia
				 if ($resultSP2[$j]>$rango[0] && $resultSP2[$j]<$rango[1]) {
				 		$acep1[]=$resultSP1[$i]; //id origen
				 		$acep2[]=$resultSP2[$j]; //id seq2
				 }
	 	}
 	}else{
 		$resul.= "Pseudoscura: No paso prueba de distancia";
 	}

	if (count($resultSP3)!=0) { 		  //tercera sequencia
	for ($j=0; $j <count($resultSP3) ; $j++) {  	//segunda sequencia
				 if ($resultSP3[$j]>$rango[0] && $resultSP3[$j]<$rango[1]) {
				 		$acep1[]=$resultSP1[$i]; //id origen
				 		$acep3[]=$resultSP3[$j]; //id seq2
				 }
	 	}
	}else{

		$resul.= "Virilis No paso prueba de distancia";	
	}

 }

echo  "<br>Zona reservada";

for ($t=0; $t <count($acep1) ; $t++){ //zona conservada 
	$rango2[0]=$acep[$t]-$txtNpares;	//limit inferior
	$zonaConservada=substr($resultSP1,$rango2[0],($txtNpares*2)); //limit superior
	

	if (count($acep2)!=0) {
		for ($u=0; $u <count($acep2) ; $u++){ 		
			$cadComparacion2=substr($resultSP2,$rango1[0],($txtNpares*2));

			for ($i=0; $i <(($txtNpares*2)+1) ; $i++) { 
				if((ord($zonaConservada[$i])-ord($cadComparacion2[$i]))>0 )$h++;
			}	

			if(($txtConservacion*(($txtNpares*2)+1))>=$h){
				$conservado[$t][$u]=$resultSP1[$i];
				$hh++;
			}
		}

		if ($hh==count($acep2)) {
			$resul.= "<br>Motifs: $t conservado!";
			$resul.= "<br>index: ".$conservado[$t];
		}
		
	}else{
		$resul.= "Pseudoscura: No paso prueba de zona consercvada";
	}



	if (count($acep3)!=0) {
		for ($u=0; $u <count($acep3) ; $u++){ 		
			$cadComparacion2=substr($resultSP2,$rango1[0],($txtNpares*2));

			for ($i=0; $i <(($txtNpares*2)+1) ; $i++) { 
				if((ord($zonaConservada[$i])-ord($cadComparacion2[$i]))>0 )$h++;
			}	

			if(($txtConservacion*(($txtNpares*2)+1))>=$h){
				$conservado[$t][$u]=$resultSP1[$i];
				$hh++;
			}
		}

		if ($hh==count($acep3)) {
			$resul.="<br>Motifs: $t conservado!";
			$resul.= "<br>index: ".$conservado[$t];
		}
		
	}else{
			$resul.= "Virilis: No paso prueba de zona consercvada";
	}



	}
}else{
	$resul= "<h4>No existe coincidencia  patron</h4>";
	echo $reporte."<br>".$resul;
}





?>